language: c

env:
    - SMVERSION=1.7
    - SMVERSION=1.8
    - SMVERSION=1.9

matrix:
    fast_finish: true
    allow_failures:
    - env: SMVERSION=1.7
    - env: SMVERSION=1.8
    - env: SMVERSION=1.9

before_install:
    - sudo apt-get update
    - sudo apt-get install gcc-multilib
    - sudo apt-get install lib32stdc++6

before_script:
    - cd game_upload/Old_serverside_\(1.5.3-1.8\)
    - wget -q "http://www.sourcemod.net/latest.php?version=$SMVERSION&os=linux" -O sourcemod.tar.gz
    - tar -xzf sourcemod.tar.gz
    - cd addons/sourcemod/scripting/
    - chmod +x spcomp
    - chmod +x compile.sh

script:
    - ./compile.sh sbpp_admcfg.sp sbpp_checker.sp sbpp_comms.sp sbpp_main.sp sbpp_sleuth.sp
